import { AgentInsight, Fixture, Player, Team } from "@/lib/types";

export const teams: Team[] = [
  {
    id: "arg", slug: "argentina", name: "Argentina",
    group: "A", confederation: "CONMEBOL", flagCode: "ar",
    powerIndex: 90, formIndex: 86, goalsFor: 8, goalsAgainst: 3,
  },
  {
    id: "fra", slug: "france", name: "France",
    group: "A", confederation: "UEFA", flagCode: "fr",
    powerIndex: 92, formIndex: 84, goalsFor: 9, goalsAgainst: 4,
  },
  {
    id: "jpn", slug: "japan", name: "Japan",
    group: "A", confederation: "AFC", flagCode: "jp",
    powerIndex: 78, formIndex: 81, goalsFor: 5, goalsAgainst: 4,
  },
  {
    id: "usa", slug: "united-states", name: "United States",
    group: "A", confederation: "CONCACAF", flagCode: "us",
    powerIndex: 80, formIndex: 79, goalsFor: 4, goalsAgainst: 5,
  },
  {
    id: "bra", slug: "brazil", name: "Brazil",
    group: "B", confederation: "CONMEBOL", flagCode: "br",
    powerIndex: 91, formIndex: 87, goalsFor: 10, goalsAgainst: 3,
  },
  {
    id: "eng", slug: "england", name: "England",
    group: "B", confederation: "UEFA", flagCode: "gb-eng",
    powerIndex: 89, formIndex: 83, goalsFor: 7, goalsAgainst: 3,
  },
  {
    id: "mar", slug: "morocco", name: "Morocco",
    group: "B", confederation: "CAF", flagCode: "ma",
    powerIndex: 81, formIndex: 80, goalsFor: 4, goalsAgainst: 4,
  },
  {
    id: "kor", slug: "south-korea", name: "South Korea",
    group: "B", confederation: "AFC", flagCode: "kr",
    powerIndex: 79, formIndex: 77, goalsFor: 3, goalsAgainst: 6,
  },
];

const SOFIFA = (id: number) => `https://cdn.sofifa.net/players/${id}/25_120.png`;

export const players: Player[] = [
  { id: "arg-alv", teamId: "arg", name: "Julian Alvarez",      position: "FWD", goals: 3, assists: 1, yellowCards: 0, redCards: 0, status: "available",  overall: 84, photoUrl: SOFIFA(248212) },
  { id: "arg-mac", teamId: "arg", name: "Alexis Mac Allister", position: "MID", goals: 1, assists: 2, yellowCards: 1, redCards: 0, status: "available",  overall: 85, photoUrl: SOFIFA(241682) },
  { id: "arg-rom", teamId: "arg", name: "Cristian Romero",     position: "DEF", goals: 0, assists: 0, yellowCards: 2, redCards: 0, status: "doubtful",   overall: 86, photoUrl: SOFIFA(209331) },

  { id: "fra-mba", teamId: "fra", name: "Kylian Mbappe",       position: "FWD", goals: 4, assists: 1, yellowCards: 0, redCards: 0, status: "available",  overall: 91, photoUrl: SOFIFA(231747) },
  { id: "fra-grz", teamId: "fra", name: "Antoine Griezmann",   position: "MID", goals: 2, assists: 3, yellowCards: 1, redCards: 0, status: "available",  overall: 86, photoUrl: SOFIFA(190871) },
  { id: "fra-kou", teamId: "fra", name: "Randal Kolo Muani",   position: "FWD", goals: 1, assists: 1, yellowCards: 0, redCards: 0, status: "available",  overall: 83, photoUrl: SOFIFA(244872) },

  { id: "jpn-kub", teamId: "jpn", name: "Takefusa Kubo",       position: "FWD", goals: 2, assists: 2, yellowCards: 1, redCards: 0, status: "available",  overall: 84, photoUrl: SOFIFA(242299) },
  { id: "jpn-min", teamId: "jpn", name: "Kaoru Mitoma",        position: "MID", goals: 1, assists: 2, yellowCards: 0, redCards: 0, status: "available",  overall: 82, photoUrl: SOFIFA(251024) },
  { id: "jpn-ito", teamId: "jpn", name: "Junya Ito",           position: "FWD", goals: 1, assists: 0, yellowCards: 1, redCards: 0, status: "injured",    overall: 78, photoUrl: SOFIFA(234571) },

  { id: "usa-pul", teamId: "usa", name: "Christian Pulisic",   position: "FWD", goals: 2, assists: 1, yellowCards: 1, redCards: 0, status: "available",  overall: 82, photoUrl: SOFIFA(220834) },
  { id: "usa-bal", teamId: "usa", name: "Folarin Balogun",     position: "FWD", goals: 1, assists: 0, yellowCards: 0, redCards: 0, status: "available",  overall: 77, photoUrl: SOFIFA(261399) },
  { id: "usa-mck", teamId: "usa", name: "Weston McKennie",     position: "MID", goals: 0, assists: 1, yellowCards: 2, redCards: 0, status: "suspended",  overall: 78, photoUrl: SOFIFA(230748) },

  { id: "bra-vin", teamId: "bra", name: "Vinicius Junior",     position: "FWD", goals: 3, assists: 2, yellowCards: 1, redCards: 0, status: "available",  overall: 92, photoUrl: SOFIFA(260098) },
  { id: "bra-rod", teamId: "bra", name: "Rodrygo",             position: "FWD", goals: 3, assists: 1, yellowCards: 0, redCards: 0, status: "available",  overall: 85, photoUrl: SOFIFA(261025) },
  { id: "bra-cas", teamId: "bra", name: "Casemiro",            position: "MID", goals: 1, assists: 1, yellowCards: 2, redCards: 0, status: "doubtful",   overall: 85, photoUrl: SOFIFA(175767) },

  { id: "eng-sak", teamId: "eng", name: "Bukayo Saka",         position: "FWD", goals: 2, assists: 2, yellowCards: 0, redCards: 0, status: "available",  overall: 86, photoUrl: SOFIFA(256561) },
  { id: "eng-bel", teamId: "eng", name: "Jude Bellingham",     position: "MID", goals: 2, assists: 2, yellowCards: 1, redCards: 0, status: "available",  overall: 88, photoUrl: SOFIFA(246268) },
  { id: "eng-kee", teamId: "eng", name: "Jordan Pickford",     position: "GK",  goals: 0, assists: 0, yellowCards: 1, redCards: 0, status: "available",  overall: 82, photoUrl: SOFIFA(199956) },

  { id: "mar-ens", teamId: "mar", name: "Youssef En-Nesyri",   position: "FWD", goals: 2, assists: 0, yellowCards: 1, redCards: 0, status: "available",  overall: 80, photoUrl: SOFIFA(243726) },
  { id: "mar-ziy", teamId: "mar", name: "Hakim Ziyech",        position: "MID", goals: 1, assists: 2, yellowCards: 1, redCards: 0, status: "available",  overall: 80, photoUrl: SOFIFA(222028) },
  { id: "mar-amr", teamId: "mar", name: "Sofyan Amrabat",      position: "MID", goals: 0, assists: 1, yellowCards: 3, redCards: 0, status: "available",  overall: 79, photoUrl: SOFIFA(239316) },

  { id: "kor-son", teamId: "kor", name: "Son Heung-min",       position: "FWD", goals: 1, assists: 1, yellowCards: 0, redCards: 0, status: "available",  overall: 87, photoUrl: SOFIFA(200826) },
  { id: "kor-hwa", teamId: "kor", name: "Hwang Hee-chan",      position: "FWD", goals: 1, assists: 0, yellowCards: 1, redCards: 0, status: "available",  overall: 80, photoUrl: SOFIFA(231466) },
  { id: "kor-kim", teamId: "kor", name: "Kim Min-jae",         position: "DEF", goals: 0, assists: 0, yellowCards: 2, redCards: 1, status: "suspended",  overall: 85, photoUrl: SOFIFA(246419) },
];

export const fixtures: Fixture[] = [
  {
    id: "f1",
    stage: "group",
    dateUtc: "2026-06-11T18:00:00Z",
    homeTeamId: "arg",
    awayTeamId: "usa",
    status: "finished",
    homeScore: 2,
    awayScore: 1,
    events: [
      { minute: 12, type: "goal", playerId: "arg-alv", teamId: "arg", detail: "Open play" },
      { minute: 46, type: "goal", playerId: "usa-pul", teamId: "usa", detail: "Penalty" },
      { minute: 78, type: "goal", playerId: "arg-mac", teamId: "arg", detail: "Set piece" },
    ],
  },
  {
    id: "f2",
    stage: "group",
    dateUtc: "2026-06-11T21:00:00Z",
    homeTeamId: "fra",
    awayTeamId: "jpn",
    status: "finished",
    homeScore: 3,
    awayScore: 1,
    events: [
      { minute: 18, type: "goal", playerId: "fra-mba", teamId: "fra", detail: "Transition" },
      { minute: 54, type: "goal", playerId: "fra-grz", teamId: "fra", detail: "Through ball" },
      { minute: 66, type: "goal", playerId: "jpn-kub", teamId: "jpn", detail: "Counter" },
      { minute: 83, type: "goal", playerId: "fra-kou", teamId: "fra", detail: "Header" },
    ],
  },
  {
    id: "f3",
    stage: "group",
    dateUtc: "2026-06-12T18:00:00Z",
    homeTeamId: "bra",
    awayTeamId: "kor",
    status: "finished",
    homeScore: 3,
    awayScore: 0,
    events: [
      { minute: 8, type: "goal", playerId: "bra-vin", teamId: "bra", detail: "Counter" },
      { minute: 35, type: "goal", playerId: "bra-rod", teamId: "bra", detail: "Cutback" },
      { minute: 81, type: "goal", playerId: "bra-rod", teamId: "bra", detail: "Long range" },
      { minute: 59, type: "yellow", playerId: "kor-kim", teamId: "kor", detail: "Tactical foul" },
    ],
  },
  {
    id: "f4",
    stage: "group",
    dateUtc: "2026-06-12T21:00:00Z",
    homeTeamId: "eng",
    awayTeamId: "mar",
    status: "finished",
    homeScore: 1,
    awayScore: 1,
    events: [
      { minute: 27, type: "goal", playerId: "eng-bel", teamId: "eng", detail: "Late run" },
      { minute: 71, type: "goal", playerId: "mar-ens", teamId: "mar", detail: "Header" },
      { minute: 74, type: "yellow", playerId: "eng-kee", teamId: "eng", detail: "Time wasting" },
    ],
  },
  {
    id: "f5",
    stage: "group",
    dateUtc: "2026-06-15T18:00:00Z",
    homeTeamId: "fra",
    awayTeamId: "usa",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f6",
    stage: "group",
    dateUtc: "2026-06-15T21:00:00Z",
    homeTeamId: "arg",
    awayTeamId: "jpn",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f7",
    stage: "group",
    dateUtc: "2026-06-16T18:00:00Z",
    homeTeamId: "eng",
    awayTeamId: "kor",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f8",
    stage: "group",
    dateUtc: "2026-06-16T21:00:00Z",
    homeTeamId: "bra",
    awayTeamId: "mar",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f9",
    stage: "group",
    dateUtc: "2026-06-20T18:00:00Z",
    homeTeamId: "jpn",
    awayTeamId: "usa",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f10",
    stage: "group",
    dateUtc: "2026-06-20T18:00:00Z",
    homeTeamId: "arg",
    awayTeamId: "fra",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f11",
    stage: "group",
    dateUtc: "2026-06-21T21:00:00Z",
    homeTeamId: "mar",
    awayTeamId: "kor",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
  {
    id: "f12",
    stage: "group",
    dateUtc: "2026-06-21T21:00:00Z",
    homeTeamId: "bra",
    awayTeamId: "eng",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    events: [],
  },
];

export const seedInsights: AgentInsight[] = [
  {
    id: "i1",
    agent: "Strength Agent",
    severity: "info",
    createdAt: "2026-04-13T09:00:00Z",
    summary: "France and Brazil remain highest baseline teams by blended power and form.",
    impact: "Champion race concentrated around four teams with tight variance between France and Brazil.",
  },
  {
    id: "i2",
    agent: "Player Signal Agent",
    severity: "warning",
    createdAt: "2026-04-13T09:10:00Z",
    summary: "Japan and USA each carry one key doubtful or suspended midfield profile.",
    impact: "Assist creation in high-pressure matches may dip, reducing upset potential by ~4-6%.",
  },
  {
    id: "i3",
    agent: "Risk Agent",
    severity: "critical",
    createdAt: "2026-04-13T09:14:00Z",
    summary: "Group B discipline profile is unstable with elevated yellow accumulation risk.",
    impact: "Card-related suspensions can alter quarterfinal pathways and confidence scores.",
  },
];
